Formulir/urls.py
from django.urls import path
from . import views

app_name = "Formulir"
urlpatterns = [
    path('', views.formPage, name="formulir"),
    path('listForm/', views.listForm, name="listForm"),
    path('cariForm/', views.cariForm, name="cariForm"),
    path('Data/', views.Data, name="Data"),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

tk2_e12/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('artikel/', include('artikel.urls')),
    path('', include('main.urls')),
    path('Form/', include('Formulir.urls'), name="Formulir"),
    path('', include('login.urls')),
]

Formulir/models.py
from django.db import models

class covidTest(models.Model):
    Gender = (
        ('', 'Choose..'),
        ('Laki-laki', 'Laki-laki'),
        ('Perempuan', 'Perempuan'),
    )
    Namatest = (
        ('', 'Choose..'),
        ('Rapid Test', 'Rapid Test'),
        ('Swab Test', 'Swab Test'),
    )
    Provinsi = (
        ('', 'Provinsi'),
        ('Aceh', 'Aceh'),
        ('Bali', 'Bali'),
        ('Banten', 'Banten'),
        ('Bengkulu', 'Bengkulu'),
        ('DI Yogyakarta', 'DI Yogyakarta'),
        ('DKI Jakarta', 'DKI Jakarta'),
        ('Gorontalo', 'Gorontalo'),
        ('Jambi', 'Jambi'),
        ('Jawa Barat', 'Jawa Barat'),
        ('Jawa Tengah', 'Jawa Tengah'),
        ('Jawa Timur', 'Jawa Timur'),
        ('Kalimantan Barat', 'Kalimantan Barat'),
        ('Kalimantan Selatan', 'Kalimantan Selatan'),
        ('Kalimantan Tengah', 'Kalimantan Tengah'),
        ('Kalimantan Timur', 'Kalimantan Timur'),
        ('Kalimantan Utara', 'Kalimantan Utara'),
        ('Kepulauan Belitung', 'Kepualauan Belitung'),
        ('Kepulauan Riau', 'Kepulauan Riau'),
        ('Lampung', 'Lampung'),
        ('Maluku', 'Maluku'),
        ('Maluku Utara', 'Maluku Utara'),
        ('Nusa Tenggara Barat', 'Nusa Tenggara Barat'),
        ('Nusa Tenggara Timur', 'Nusa Tenggara Timur'),
        ('Riau', 'Riau'),
        ('Sulawesi Barat', 'Sulawesi Barat'),
        ('Sulawesi Selatan', 'Sulawesi Selatan'),
        ('Sulawesi Tengah', 'Sulawesi Tengah'),
        ('Sulawesi Tenggara', 'Sulawesi Tenggara'),
        ('Sulawesi Utara', 'Sulawesi Utara'),
        ('Sumatera Barat', 'Sumatera Barat'),
        ('Sumatera Selatan', 'Sumatera Selatan'),
        ('Sumatera Utara', 'Sumatera Utara'),
        ('Papua', 'Papua'),
        ('Papua Barat', 'Papua Barat'),
    )

    Nama_Lengkap = models.CharField(max_length=70)
    Usia = models.PositiveIntegerField()
    No_Telp = models.PositiveIntegerField()
    Jenis_Kelamin = models.CharField(max_length=10, choices=Gender, default='')
    Alamat = models.TextField(max_length=150)
    Nama_Test = models.CharField(max_length=20, choices=Namatest, default='')
    Lokasi_Test = models.CharField(max_length=50, choices=Provinsi, default='')
        
    def __str__(self):
        return self.Nama_Lengkap

Formulir/forms.py
from django import forms
from .models import covidTest

class formTest(forms.ModelForm):
    class Meta:
        model = covidTest
        fields = ('Nama_Lengkap', 'Usia', 'No_Telp', 'Jenis_Kelamin', 'Alamat', 'Nama_Test', 'Lokasi_Test')
        widgets = {
            'Nama_Lengkap' : forms.TextInput(attrs={'class': 'form-control', 'placeholder' : 'Nama Lengkap'}),
            'Usia' : forms.TextInput(attrs={'class': 'form-control', 'placeholder' : '00'}),
            'No_Telp' : forms.TextInput(attrs={'class': 'form-control', 'placeholder' : '08123456789'}),
            'Jenis_Kelamin' : forms.Select(attrs={'class': 'form-control formselect'}),
            'Alamat' : forms.Textarea(attrs={'class': 'form-control textForm', 'placeholder' : 'jl. nama jalan, kecamatan, kota, kode pos', 'rows':5}),
            'Nama_Test' : forms.Select(attrs={'class': 'form-control formselect'}),
            'Lokasi_Test' : forms.Select(attrs={'class': 'form-control formselect'}),
        }

Formulir/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import covidTest
from .forms import formTest
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import json

@login_required(login_url='/login/')
def formPage(request):
    formulir = formTest()
    if request.method == "POST":
        formulir = formTest(request.POST)
        if formulir.is_valid():
            formulir.save()
            return render(request, 'respon.html', {})
            # return JsonResponse(load_data, safe=False)
            # return JsonResponse({'message': 'success'})
        else:
            messages.error(request, " ")
    
    context = {
        'form' : formulir
    }
    return render(request, 'formulir.html', context)

def Data(request):
    dict_data = '[{"id":"%s", "Nama_Lengkap":"%s", "Usia":"%s", "No_Telp":"%s", "Jenis_Kelamin":"%s", "Alamat":"%s", "Nama_Test":"%s", "Lokasi_Test":"%s"}]' %(form.id, form.Nama_Lengkap, form.Usia, form.No_Telp ,form.Jenis_Kelamin, form.Alamat, form.Nama_Test, form.Lokasi_Test)
    load_data = json.loads(dict_data)
    # return render(request, 'respon.html', {})
    return JsonResponse(load_data, safe=False)

@login_required(login_url='/login/')
def listForm(request):
    list_formulir = covidTest.objects.all()
    context = {'listForm':list_formulir}
    return render(request, 'list.html', context)

def cariForm(request):
    cari = request.GET['q']
    cekContain = covidTest.objects.filter(Nama_Lengkap__icontains=cari) | covidTest.objects.filter(Usia__icontains=cari) | covidTest.ojects.filter(No_telp__icontains=cari) | covidTest.objects.filter(Jenis_Kelamin__icontains=cari) | covidTest.objects.filter(Alamat__icontains=cari) | covidTest.objects.filter(Nama_test__icontains=cari) | covidTest.objects.filter(Lokasi_Test__icontains=cari)
    data = cekContain.values()
    return JsonResponse(data, safe=False)

Formulir/templates/formulir.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@800&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Oxygen&display=swap" rel="stylesheet">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<style>
.button {
    background-color: #394867;
    border: none;
    color: white;
    padding: 12px 40px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 15px;
    cursor: pointer;
    border-radius: 15px;
}
.container{
    background-color:#f1f6f9;
    border-radius:75px;
    border-style:solid;
    border-color:#14274e;
    padding:35px;
    width:50%;
}
.judul{
    color:#394867;
    text-align:center;
}
.containerForm{
    margin-top: 45px;
}
.form-row{
    text-align:left;
    color:#394867;
}
.ukForm{
    width: 450px;
}
.form-control{
    border-radius: 25px;
    border-color:#394867;
}
.formselect{
    border-radius: 10px;
    border-color:#394867;
    width: 150px;
}
.textForm{
    border-radius: 10px;
    border-color:#394867;
}

@media only screen and (max-width: 1080px){
    .container {
        width : 55%;
    }
    .ukForm{
        width: 400px;
    }
    h1.judul {
        font-size: 35px;
    }
}

@media only screen and (max-width: 860px){
    .container {
        width : 60%;
    }
    .ukForm{
        width: 350px;
    }
    h1.judul {
        font-size: 35px;
    }
}

@media only screen and (max-width: 720px){
    .container {
        width : 65%;
    }
    .ukForm{
        width: 300px;
    }
    h1.judul {
        font-size: 35px;
    }
}

@media only screen and (max-width: 620px){
    .container {
        width : 70%;
    }
    .ukForm{
        width: 250px;
    }
    h1.judul {
        font-size: 30px;
    }
}

@media only screen and (max-width: 415px){
    .container {
        width : 78%;
    }
    .ukForm{
        width: 200px;
    }
    h1.judul {
        font-size: 27px;
    }
    .button {
        padding: 12px 37px;
        font-size: 13px;
    }
}

@media only screen and (max-width: 315px){
    .container {
        width : 80%;
    }
    .ukForm{
        width: 170px;
    }
    h1.judul {
        font-size: 22px;
    }
}

@media only screen and (max-width: 250px){
    .container {
        width : 100%;
    }
    .ukForm{
        width: 140px;
    }
    h1.judul {
        font-size: 18px;
    }
    .formselect{
        width: 120px;
    }
    .button {
        padding: 10px 34px;
        font-size: 13px;
    }
}

@media only screen and (max-width: 170px){
    .container {
        width : 100%;
    }
    .ukForm{
        width: 120px;
    }
    h1.judul {
        font-size: 16px;
    }
    .formselect{
        width: 100px;
    }
    .button {
        padding: 10px 32px;
        font-size: 13px;
    }
}

</style>
{% endblock meta %}

{% block content %}
    <br></br>
    <div class="container">
        <h1 class="judul" style="font-family: 'Open Sans', sans-serif;">FORMULIR</h1>
        <div class="d-flex justify-content-center containerForm">
            <div id="form" class="form-row">
                <div class="col-auto">
                    <div class="form-group ukForm" style="font-family: 'Oxygen', sans-serif;">
                        <form action="" method="post">
                        {% csrf_token %}
                        <div class="field">
                            <label for="{{ form.Nama_Lengkap.id_for_label }}" class="label">Nama Lengkap:</label>
                            {{ form.Nama_Lengkap }}
                        </div>
                        <br>
                        <div class="field">
                            <label for="{{ form.Usia.id_for_label }}" class="label">Usia:</label>
                            {{ form.Usia }}
                        </div>
                        <br>
                        <div class="field">
                            <label for="{{ form.No_Telp.id_for_label }}" class="label">No. Telp:</label>
                            {{ form.No_Telp }}
                        </div>
                        <br>
                        <div class="field">
                            <label for="{{ form.Jenis_Kelamin.id_for_label }}" class="label">Jenis Kelamin:</label>
                            {{ form.Jenis_Kelamin }}
                        </div>
                        <br>
                        <div class="field">
                            <label for="{{ form.Alamat.id_for_label }}" class="label">Alamat:</label>
                            {{ form.Alamat }}
                        </div>
                        <br>
                        <div class="field">
                            <label for="{{ form.Nama_Test.id_for_label }}" class="label">Nama test:</label>
                            {{ form.Nama_Test }}
                        </div>
                        <br>
                        <div class="field">
                            <label for="{{ form.Lokasi_Test.id_for_label }}" class="label">Lokasi test:</label>
                            {{ form.Lokasi_Test }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="d-flex justify-content-center">
        <input id="btn" class="button active" type="submit" value='Daftar'>
    </div>
</div>

<script>
    {% if messages %}
        {% comment %} {% for message in messages %} {% endcomment %}
            $(document).ready(function(){
                alert("Form is invalid");
            });
        {% comment %} {% endfor %} {% endcomment %}
    {% else %}
        {% comment %} $(document).ready(function(){ {% endcomment %}
            $("#form").on("submit", function (e) {
                e.preventDefault();
                var serialized = $(this).serialize();
                console.log("create post is working!")
                $.ajax({
                    dataType: 'json',
                    type: 'POST',
                    url:"{% url 'Formulir:Data' %}",
                    data: {
                        serialized,
                        'csrfmiddlewaretoken' : $("input["name=csrfmiddlewaretoken"]").val()
                    }
                    success: function (pesan) {
                        // clear form
                        if (pesan.message === 'success') {
                            alert('Event has been successfully added!');
                            $('form').trigger("reset");
                        }
                    },
                });
            });
        {% comment %} }); {% endcomment %}

        function getCookie(c_name){
            if (document.cookie.length > 0){
                c_start = document.cookie.indexOf(c_name + "=");
                if (c_start != -1){
                    c_start = c_start + c_name.length + 1;
                    c_end = document.cookie.indexOf(";", c_start);
                    if (c_end == -1) c_end = document.cookie.length;
                    return unescape(document.cookie.substring(c_start,c_end));
                }
            }
            return "";
        }

        $(function () {
            $.ajaxSetup({
                headers: { "X-CSRFToken": getCookie("csrftoken") }
            });
        });

    {% endif %}
</script>
{% endblock %}

Formulir/templates/list.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@800&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Oxygen&display=swap" rel="stylesheet">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <style>
        .judul{
            color:#394867;
            text-align:center;
        }
        .containerForm{
            font-size: 15px;
        }
    }

    @media only screen and (max-width: 500px){
        h1.judul {
            font-size: 27px;
        }
        .containerForm{
            font-size: 13px;
        }
    </style>
{% endblock meta %}
{% block content %}
    <br></br>
    <div class="container">
        <h1 class="judul" style="font-family: 'Open Sans', sans-serif;">DAFTAR SELURUH PESERTA TEST</h1>
        <br>
        <div class="container">
            <div class="input">
                <input id="search" class="form-control" placeholder="Search here..">
            </div>
        </div>
        <br>
        <div class="d-flex justify-content-center containerForm">
            
            {% comment %} <div>
                <table class="table">
                    <tbody id="results">
                    </tbody>
                </table>
            </div> {% endcomment %}
            <div class="table-responsive">
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">No.</th>
                            <th scope="col">Nama Lengkap</th>
                            <th scope="col">Usia</th>
                            <th scope="col">No. Telp</th>
                            <th scope="col">Jenis Kelamin</th>
                            <th scope="col">Alamat</th>
                            <th scope="col">Nama Test</th>
                            <th scope="col">Lokasi Test</th>
                        </tr>
                    </thead>
                    <tbody id="results">
                    </tbody>
                    <tbody>
                        {% for i in listForm %}
                        <tr>
                            <th scope="row">{{i.id}}</th>
                            <td>{{i.Nama_Lengkap}}</td>
                            <td>{{i.Usia}}</td>
                            <td>{{i.No_Telp}}</td>
                            {% if i.Jenis_Kelamin == 'Laki-laki' %}
                                <td>L</td>
                            {% else %}
                                <td>P</td>
                            {% endif %}
                            <td>{{i.Alamat}}</td>
                            <td>{{i.Nama_Test}}</td>
                            <td>{{i.Lokasi_Test}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <script>
        $(document).ready(function(){
            $("#search").keyup(function(){

                var srch = $("#search").val();
                console.log(srch);
                ajaxsearch(srch);
            });
        });

        function ajaxsearch(search){
            $.ajax({
                url: "/Form/cariForm/?q=" + search,
                data:{
                    'q' : search,
                    'csrfmiddlewaretoken' : $("input["name=csrfmiddlewaretoken"]").val()
                },
                dataType: 'json',
                success: function(data){
                    console.log(data);
                    var arrayData = data;
                    $("#results").empty()
                    for (i = 0; i < arrayData.length; i++){
                        var index = arrayData.id[i].id;
                        var Nama_Lengkap = index.Nama_Lengkap;
                        var Usia = index.Usia;
                        var No_Telp = index.No_Telp;
                        var Jenis_Kelamin = index.Jenis_Kelamin;
                        var Alamat = index.Alamat;
                        var Nama_Test = index.Nama_Test;
                        var Lokasi_Test = index.Lokasi_Test;
                        if (Jenis_Kelamin == 'Laki-Laki'){
                            results.innerHTML += "<tr><th scope="row">" + index + "</th><td>" + Nama_Lengkap + "</td><td>" + Usia + "</td><td>" + No_Telp + "</td><td>L</td><td>" + Alamat + "</td><td>" + Nama_Test + "</td><td>" + Lokasi_Test + "</td></tr>"
                        }
                        else{
                            results.innerHTML += "<tr><th scope="row">" + index + "</th><td>" + Nama_Lengkap + "</td><td>" + Usia + "</td><td>" + No_Telp + "</td><td>P</td><td>" + Alamat + "</td><td>" + Nama_Test + "</td><td>" + Lokasi_Test + "</td></tr>"
                        }
                    }
                },
                type: 'GET'
            });
        }
    {% endblock content %}

Formulir/templates/respon.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@800&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Oxygen&display=swap" rel="stylesheet">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
    <style>
    .container{
        background-image: url("/static/img/maskerBack.png");
        background-size: 100%;
        background-repeat: no-repeat;
        width: 100%;
        height: auto;
        margin: -15px 180px;
        padding: 150px 135px;
    }
    h1.judul{
        text-align: center;
        color: white;
        font-size: 60px;
    }
    .button {
            background-color: #394867;
            border: none;
            color: white;
            padding: 12px 30px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 13px;
            cursor: pointer;
            border-radius: 15px;
    }

    @media only screen and (max-width: 1180px){
        h1.judul {
            font-size: 50px;
        }
    }

    @media only screen and (max-width: 1100px){
        h1.judul {
            font-size: 40px;
        }
        .container{
            padding: 120px 120px;
        }
        .button{
            padding: 12px 25px;
            font-size: 11px;
        }
    }

    @media only screen and (max-width: 965px){
        h1.judul {
            font-size: 35px;
        }
        .container{
            padding: 110px 110px;
        }
        .button{
            padding: 12px 25px;
            font-size: 11px;
        }
    }

    @media only screen and (max-width: 900px){
        h1.judul {
            font-size: 31px;
        }
        .container{
            padding: 100px 100px;
        }
        .button{
            padding: 12px 25px;
            font-size: 11px;
        }
    }

    @media only screen and (max-width: 768px){
        h1.judul {
            font-size: 30px;
        }
        .button{
            padding: 12px 25px;
            font-size: 10px;
        }
    }

    @media only screen and (max-width: 475px){
        h1.judul {
            font-size: 25px;
        }
        .container{
            padding: 70px 50px;
        }
        .button{
            padding: 12px 25px;
            font-size: 10px;
        }
    }

    @media only screen and (max-width: 380px){
        h1.judul {
            font-size: 20px;
        }
        .container{
            padding: 60px 50px;
        }
        .button{
            padding: 8px 18px;
            font-size: 7px;
        }
    }

    @media only screen and (max-width: 320px){
        h1.judul {
            font-size: 20px;
        }
        .container{
            padding: 50px 50px;
        }
        .button{
            padding: 8px 18px;
            font-size: 7px;
        }
    }

    @media only screen and (max-width: 290px){
        h1.judul {
            font-size: 15px;
        }
        .container{
            padding: 40px 50px;
        }
        .button{
            padding: 6px 15px;
            font-size: 7px;
        }
    }

    @media only screen and (max-width: 250px){
        h1.judul {
            font-size: 12px;
        }
        .container{
            padding: 40px 50px;
        }
        .button{
            padding: 6px 15px;
            font-size: 7px;
        }
    }

    @media only screen and (max-width: 220px){
        h1.judul {
            font-size: 12px;
        }
        .container{
            padding: 30px 40px;
        }
        .button{
            padding: 6px 15px;
            font-size: 7px;
        }
    }

    @media only screen and (max-width: 202px){
        h1.judul {
            font-size: 10px;
        }
        .container{
            padding: 30px 40px;
        }
        .button{
            padding: 4px 10px;
            font-size: 5px;
        }
    }

    @media only screen and (max-width: 190px){
        h1.judul {
            font-size: 7px;
        }
        .container{
            padding: 20px 40px;
        }
        .button{
            padding: 4px 10px;
            font-size: 5px;
        }
    }

    </style>
{% endblock meta %}
{% block content %}
    <br></br>
    <div class="d-flex justify-content-center">
        <div class="container">
            <h1 class="judul">TERIMA KASIH TELAH MENDAFTAR</h1>
            <br>
            <div class="d-flex justify-content-center">
                <div class="col-sm">
                    <div class="d-flex justify-content-center">
                    </div>
                </div>
                <div class="col-sm">
                    <div class="d-flex justify-content-center">
                        <a href="/Form/" class="btn btn-md active clr button" role="button" aria-pressed="true">Homepage</a>
                    </div>
                </div>
                <div class="col-sm">
                    <div class="d-flex justify-content-center">
                        <a href="/Form/listForm" class="btn btn-md active clr button" role="button" aria-pressed="true">Cek Formulir</a>
                    </div>
                </div>
                <div class="col-sm">
                    <div class="d-flex justify-content-center">
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock content %}